### ISSUE TITLE
PostgreSQL 9.6 base image

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-dockerfiles#3]
We're using PostgreSQL with SSL connection enabled. We want to have a base image that generates a self-signed certificate for development.

Since `postgres:9.6` declares a `VOLUME` for `/var/lib/postgres/data/` we can use this for sharing the `server.crt` and `server.key` with the client containters

```yaml
version: "3"

services:
  db:
    image: postgres:9.6
    volumes:
      - pg-data:/var/lib/postgresql/data
  server:
    image: alpine:3.8
    command: tail -f /dev/null
    volumes:
      - pg-data:/pg-data:ro
    depends_on:
      - db
volumes:
  pg-data:
```
In this case the `server` service can read the required files from `/pg-data`
